import TCP
import UDP
import Statistical as sts
import Session

def feature_map():
    return {'SYN_tcp_scale':TCP.SYN_tcp_scale,
            'SYN_MSS':TCP.SYN_MSS,
            'SYN_tcp_winsize':TCP.SYN_tcp_winsize,
            'num_keep_alive':TCP.num_keep_alive,
            'size_histogram':sts.size_histogram,
            'packet_count':sts.packet_count,
            'min_packet_size':sts.min_packet_size,
            'max_packet_size':sts.max_packet_size,
            'mean_packet_size':sts.mean_packet_size,
            'sizevar':sts.sizevar,
            'std_time_delta':sts.std_time_delta,
            'min_time_delta':sts.min_time_delta,
            'max_time_delta':sts.max_time_delta,
            'mean_time_delta':sts.mean_time_delta,
            'peak_features':sts.peak_features,
            'fcipher_suites':Session.fcipher_suites,
            'fSSL_session_id_len':Session.fSSL_session_id_len,
            'fSSL_num_extensions':Session.fSSL_num_extensions,
            'fSSL_num_compression_methods':Session.fSSL_num_compression_methods,
            'fSSLv':Session.fSSLv,
            'fpeak_features':Session.fpeak_features,
            'bpeak_features':Session.bpeak_features,
            'std_fiat':Session.std_fiat,
            'fpackets':Session.fpackets,
            'bpackets':Session.bpackets,
            'fbytes':Session.fbytes,
            'bbytes':Session.bbytes,
            'min_fiat':Session.min_fiat,
            'min_biat':Session.min_biat,
            'max_fiat':Session.max_fiat,
            'max_biat':Session.max_biat,
            'std_biat':Session.std_biat,
            'mean_fiat':Session.mean_fiat,
            'mean_biat':Session.mean_biat,
            'min_fpkt':Session.min_fpkt,
            'min_bpkt':Session.min_bpkt,
            'max_fpkt':Session.max_fpkt,
            'max_bpkt':Session.max_bpkt,
            'std_fpkt':Session.std_fpkt,
            'std_bpkt':Session.std_bpkt,
            'mean_fpkt':Session.mean_fpkt,
            'mean_bpkt':Session.mean_bpkt,
            'mean_fttl':Session.mean_fttl}
